---
swagger: "2.0"
info:
  description: "erster Entwurf einer Script Execution Engine API, die Script COde\
    \ ausf√ºhren kann."
  version: "0.0.1"
  title: "KomMonitor Script Execution Engine API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "christian.danowski-buhren@hs-bochum.de"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8086"
basePath: "/processing"
tags:
- name: "script-engine"
  description: "Execute scripts"
schemes:
- "http"
- "https"
security:
- basicAuth: []
paths:
  /script-engine/customizableIndicatorComputation:
    post:
      tags:
      - "script-engine"
      summary: "Initiate execution of a customizable indicator computation."
      description: "Initiate execution of a customizable indicator computation."
      operationId: "postCustomizableIndicatorComputation"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "script-input"
        description: "details necessary to trigger script execution"
        required: true
        schema:
          $ref: "#/definitions/CustomizableIndicatorComputationInputType"
      responses:
        201:
          description: "Created"
          headers:
            location:
              type: "string"
              description: "identifier of the created job execution"
        401:
          description: "API key is missing or invalid"
          headers:
            WWW_Authenticate:
              type: "string"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "ScriptEngine"
  /script-engine/customizableIndicatorComputation/{jobId}:
    get:
      tags:
      - "script-engine"
      summary: "retrieve status information and/or results about executing customizable\
        \ indicator computation."
      description: "retrieve status information and/or results about executing customizable\
        \ indicator computation."
      operationId: "getCustomizableIndicatorComputation"
      produces:
      - "application/json"
      parameters:
      - name: "jobId"
        in: "path"
        description: "unique identifier of the job that performs indicator computation"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/CustomizableIndicatorComputationStatusResultType"
        400:
          description: "Invalid status value"
      x-swagger-router-controller: "ScriptEngine"
  /script-engine/defaultIndicatorComputation:
    post:
      tags:
      - "script-engine"
      summary: "Initiate execution of a default indicator computation."
      description: "Initiate execution of a default indicator computation."
      operationId: "postDefaultIndicatorComputation"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "script-input"
        description: "details necessary to trigger script execution"
        required: true
        schema:
          $ref: "#/definitions/DefaultIndicatorComputationInputType"
      responses:
        201:
          description: "Created"
          headers:
            location:
              type: "string"
              description: "identifier of the created job execution"
        401:
          description: "API key is missing or invalid"
          headers:
            WWW_Authenticate:
              type: "string"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "ScriptEngine"
  /script-engine/defaultIndicatorComputation/{jobId}:
    get:
      tags:
      - "script-engine"
      summary: "retrieve status information and/or results about executing default\
        \ indicator computation."
      description: "retrieve status information and/or results about executing default\
        \ indicator computation."
      operationId: "getDefaultIndicatorComputation"
      produces:
      - "application/json"
      parameters:
      - name: "jobId"
        in: "path"
        description: "unique identifier of the job that performs indicator computation"
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/DefaultIndicatorComputationStatusResultType"
        400:
          description: "Invalid status value"
      x-swagger-router-controller: "ScriptEngine"
securityDefinitions:
  basicAuth:
    type: "basic"
definitions:
  CustomizableIndicatorComputationInputType:
    type: "object"
    required:
    - "customProcessProperties"
    - "scriptId"
    - "targetDate"
    - "targetSpatialUnitId"
    properties:
      scriptId:
        type: "string"
        description: "the identifier of the script that contains the code to perform\
          \ the target indicator computation."
      targetDate:
        type: "string"
        format: "date"
        description: "a timestamp representing the date for which the indicator shall\
          \ be computed according to ISO 8601 (e.g. 2018-01-30)"
      targetSpatialUnitId:
        type: "string"
        description: "the identifier of the target spatial unit for which the indicator\
          \ shall be computed."
      baseIndicatorIds:
        type: "array"
        description: "a list of identifiers of base indicators that are required to\
          \ compute the target indicator. While the parameter is required, the list\
          \ may be empty if no other indicator is required for the computation."
        items:
          type: "string"
      georesourceIds:
        type: "array"
        description: "a list of identifiers of georesources that are required to compute\
          \ the target indicator. While the parameter is required, the list may be\
          \ empty if no georesource is required for the computation."
        items:
          type: "string"
      customProcessProperties:
        type: "array"
        description: "a list of custom process parameters. Using different values,\
          \ a caller may infect the target indicator computation."
        items:
          $ref: "#/definitions/ProcessPropertyType"
    description: "required input parameters to execute a customizable indicator computation"
    example:
      targetSpatialUnitId: "targetSpatialUnitId"
      scriptId: "scriptId"
      customProcessProperties:
      - dataType: "string"
        name: "name"
        value: "customValue"
      - dataType: "string"
        name: "name"
        value: "customValue"
      targetDate: "2000-01-23"
      georesourceIds:
      - "georesourceIds"
      - "georesourceIds"
      baseIndicatorIds:
      - "baseIndicatorIds"
      - "baseIndicatorIds"
  ProcessPropertyType:
    type: "object"
    required:
    - "dataType"
    - "name"
    - "value"
    properties:
      name:
        type: "string"
        description: "the name of the process input parameter"
      dataType:
        type: "string"
        description: "the data type of the process input"
        enum:
        - "string"
        - "boolean"
        - "integer"
        - "double"
      value:
        type: "string"
        description: "the value of the process parameter according to the specified\
          \ data type as string value."
    example:
      dataType: "string"
      name: "name"
      value: "value"
  CustomizableIndicatorComputationStatusResultType:
    type: "object"
    required:
    - "jobId"
    - "progress"
    - "result_geoJSON_base64"
    - "status"
    properties:
      jobId:
        type: "string"
        description: "the identifier of the job that executes the target indicator\
          \ computation."
      status:
        type: "string"
        description: "the current status of execution. Possible values are ACCEPTED,\
          \ RUNNING, FINISHED, ERROR."
        enum:
        - "ACCEPTED"
        - "RUNNING"
        - "FINISHED"
        - "ERROR"
      progress:
        type: "number"
        format: "int32"
        description: "the progress of indicator computation in percent."
      result_geoJSON_base64:
        type: "string"
        description: "the computed target indicator for the target spatial unit as\
          \ valid GeoJSON string encoded via Base64."
      error:
        type: "string"
        description: "an error message if an error occured during indicator computation.\
          \ It is only included in the response object if an error occured."
    description: "status information about the execution of the target indicator.\
      \ If the result was computed then it is also included within the response object."
    example:
      jobId: "jobId"
      result_geoJSON_base64: "result_geoJSON_base64"
      progress: 100
      error: "error"
      status: "Succeeded"
  DefaultIndicatorComputationInputType:
    type: "object"
    required:
    - "scriptId"
    - "targetIndicatorId"
    - "targetDate"
    properties:
      scriptId:
        type: "string"
        description: "the identifier of the script that contains the code to perform\
          \ the target indicator computation."
      targetIndicatorId:
        type: "string"
        description: "the identifier of the target indicator that can be computed by the associated script."
      targetDate:
        type: "string"
        format: "date"
        description: "a timestamp representing the date for which the indicator shall\
          \ be computed according to ISO 8601 (e.g. 2018-01-30)"
      baseIndicatorIds:
        type: "array"
        description: "a list of identifiers of base indicators that are required to\
          \ compute the target indicator. While the parameter is required, the list\
          \ may be empty if no other indicator is required for the computation."
        items:
          type: "string"
      georesourceIds:
        type: "array"
        description: "a list of identifiers of georesources that are required to compute\
          \ the target indicator. While the parameter is required, the list may be\
          \ empty if no georesource is required for the computation."
        items:
          type: "string"
      defaultProcessProperties:
        type: array
        description: "a list of process parameters utilizing their default values."
        items:
          $ref: "#/definitions/ProcessPropertyType"
    description: "required input parameters to execute a default indicator computation.\
      \ Default means that the process parameters/properties that infect the indicator\
      \ computation are set to default values."
    example:
      scriptId: "scriptId"
      targetIndicatorId: "targetIndicatorId"
      targetDate: "2000-01-23"
      georesourceIds:
      - "georesourceIds"
      - "georesourceIds"
      baseIndicatorIds:
      - "baseIndicatorIds"
      - "baseIndicatorIds"
      defaultProcessProperties:
      - dataType: "string"
        name: "name"
        value: "defaultValue"
      - dataType: "string"
        name: "name"
        value: "defaultValue"
  DefaultIndicatorComputationStatusResultType:
    type: "object"
    required:
    - "jobId"
    - "progress"
    - "result"
    - "status"
    properties:
      jobId:
        type: "string"
        description: "the identifier of the job that executes the default indicator\
          \ computation for all applicable spatial units."
      status:
        type: "string"
        description: "the current status of execution. Possible values are ACCEPTED,\
          \ RUNNING, FINISHED, ERROR."
        enum:
        - "ACCEPTED"
        - "RUNNING"
        - "FINISHED"
        - "ERROR"
      progress:
        type: "number"
        format: "int32"
        description: "the progress of indicator computation in percent."
      result:
        type: "array"
        description: "an array of objects containing information about indicator resources persisted within KomMonitor data management service."
        items:
          $ref: "#/definitions/PersistedIndicatorResultType"
          type: "string"
      error:
        type: "string"
        description: "an error message if an error occured during indicator computation.\
          \ It is only included in the response object if an error occured."
    description: "status information about the default execution of the target indicator."
    example:
      jobId: "jobId"
      result:
        - indicatorId: "indicatorId1"
          indicatorName: "indicatorName"
          spatialUnitId: "spatialUnitId1"
          spatialUnitName: "spatialUnitName"
          targetDate: "2018-01-01"
          urlToPersistedResource: "UrlToResource"
        - indicatorId: "indicatorId1"
          indicatorName: "indicatorName"
          spatialUnitId: "spatialUnitId2"
          spatialUnitName: "spatialUnitName"
          targetDate: "2018-01-01"
          urlToPersistedResource: "UrlToResource"
      progress: 5
      error: "error"
      status: "Created"
  PersistedIndicatorResultType:
    type: "object"
    required:
    - "indicatorId"
    - "indicatorName"
    - "spatialUnitId"
    - "spatialUnitName"
    - "targetDate"
    - "urlToPersistedResource"
    properties:
      indicatorId:
        type: "string"
        description: "the identifier of the indicator"
      indicatorName:
        type: "string"
        description: "the name of the indicator"
      spatialUnitId:
        type: "string"
        description: "the identifier of the associated spatialUnit"
      spatialUnitName:
        type: "string"
        description: "the name of the associated spatialUnit"
      targetDate:
        type: "string"
        description: "the target date according to the pattern 'YYY-MM-DD'"
      urlToPersistedResource:
        type: "string"
        description: "the URL pointing to the persisted indicator within the KomMonitor data management API."
    example:
      indicatorId: "indicatorId1"
      indicatorName: "indicatorName"
      spatialUnitId: "spatialUnitId1"
      spatialUnitName: "spatialUnitName"
      targetDate: "2018-01-01"
      urlToPersistedResource: "UrlToResource"

responses:
  UnauthorizedError:
    description: "API key is missing or invalid"
    headers:
      WWW_Authenticate:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
